[default]
TITLE = "App with login"
SECRET_KEY = "1f13965644d67dec60739fc61f51dd97"
SQLALCHEMY_DATABASE_URI = ""
SQLALCHEMY_TRACK_MODIFICATIONS = false
EXTENSIONS = [
    "app_with_login.ext.auth:init_app",
    "app_with_login.ext.database:init_app",
    "app_with_login.blueprint.routers.main:init_app",
    "app_with_login.ext.command:init_app"
]